# Generated by Django 5.2.8 on 2026-03-05 19:09

import encryption_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(blank=True, null=True, upload_to=encryption_app.models.user_directory_path)),
            ],
        ),
    ]
